<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DESKTOP-GJ67TUH" name="Maven.automation_project.Smoke.LoginTest" tests="7" failures="1" timestamp="30 Oct 2017 16:20:33 GMT" time="19.743" errors="0">
  <testcase name="Verify_User_is_Able_to_Login_With_Valid_Credentials" time="9.143" classname="Maven.automation_project.Smoke.LoginTest"/>
  <testcase name="Verify_User_is_not_Able_to_Login_With_Blank_Credentials" time="1.470" classname="Maven.automation_project.Smoke.LoginTest"/>
  <testcase name="Verify_User_is_not_Able_to_Login_With_Blank_Password" time="1.471" classname="Maven.automation_project.Smoke.LoginTest"/>
  <testcase name="Verify_User_is_not_Able_to_Login_With_Invalid_EmailAddress" time="1.581" classname="Maven.automation_project.Smoke.LoginTest"/>
  <testcase name="Verify_User_is_not_Able_to_Login_With_Invalid_Password" time="1.932" classname="Maven.automation_project.Smoke.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [Invali password.] but found [Invalid password.]">
      <![CDATA[java.lang.AssertionError: expected [Invali password.] but found [Invalid password.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Maven.automation_project.Pages.LoginPage.login_invalid_pass(LoginPage.java:106)
	at Maven.automation_project.Smoke.LoginTest.Verify_User_is_not_Able_to_Login_With_Invalid_Password(LoginTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1022)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1223)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Verify_User_is_not_Able_to_Login_With_Invalid_Password -->
  <testcase name="Verify_User_is_not_Able_to_Login_With_Invalid_Password" time="2.133" classname="Maven.automation_project.Smoke.LoginTest">
    <skipped/>
  </testcase> <!-- Verify_User_is_not_Able_to_Login_With_Invalid_Password -->
  <testcase name="Verify_User_is_not_Able_to_Login_With_Invalid_Password" time="2.013" classname="Maven.automation_project.Smoke.LoginTest">
    <skipped/>
  </testcase> <!-- Verify_User_is_not_Able_to_Login_With_Invalid_Password -->
</testsuite> <!-- Maven.automation_project.Smoke.LoginTest -->
